version: '3'

services:
  backend:
    container_name: ecommerce
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./.env:/app/.env
    networks:
      - nestjs
    depends_on:
      - database

  database:
    container_name: ecommerce
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - "3306:3306"
        - "33060:33060"
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_PASSWORD: ecommerce
      MYSQL_ROOT_PASSWORD: ecommerce
    volumes:
      - nestjs-data:/var/lib/mysql
    networks:
      - nestjs
volumes:
  nestjs-data:

networks:
  nestjs:
    driver: bridge
